name       : libnfs
version    : 1.11.0
release    : 1
source     :
    - https://github.com/sahlberg/libnfs/archive/libnfs-1.11.0.tar.gz : fc2e45df14d8714ccd07dc2bbe919e45a2e36318bae7f045cbbb883a7854640f
license    : 
    - BSD-2-Clause
    - GPL-3.0
    - LGPL-2.1
component  : programming.library
summary    : A client library for accessing NFS shares over a network.
description: |
    LIBNFS offers three different APIs: RAW, NFS ASYNC and NFS SYNC.
    
    NFSv4 is supported but only for the RAW ASYNC interface.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
