name       : libnfs
version    : 3.0.0
release    : 2
source     :
    - https://github.com/sahlberg/libnfs/archive/libnfs-3.0.0.tar.gz : 445d92c5fc55e4a5b115e358e60486cf8f87ee50e0103d46a02e7fb4618566a5
license    :
    - BSD-2-Clause
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
component  : programming.library
summary    : A client library for accessing NFS shares over a network
description: |
    LIBNFS offers three different APIs: RAW, NFS ASYNC and NFS SYNC.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
